### ISSUE TITLE
Fix Frontend

### ISSUE THREAD

**Issue by Shinigami584** [Clueless-Aware/MauiFrontend#79]
- [x] PFP detail too big mobile D
- [x] Margin top cards mobile in login page F
- [x] Title UI Artist search F
- [x] Email Staff --> remove margin left D
- [x] Edit Artwork images clamp D
- [x] Clamp table edit admin D
- [x] Edit section remove margin F
- [x] About the app --> w-100  m-top F

**Comment by Aiuola** [comment]
This has already been fixed... Closing issue
